# Use an Nginx base image
FROM nginx:alpine

# Remove default nginx web content
RUN rm -rf /usr/share/nginx/html/*

# Copy your app's static files to nginx public folder
COPY . /usr/share/nginx/html

# Expose port 80
EXPOSE 80

